name: Test minigeth

on: push

jobs:
  unit:
    name: minigeth computes correct block transitions
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Toolchain
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install golang-1.16
    - name: Build
      run: make minigeth_default_arch
    - name: Test
      run: make test_minigeth
